baseURL = 'https://mixolydianmel.github.io/blog/'
languageCode = 'en-us'
title = "Melody's Musings"
theme = 'hugo-tufte'
paginate = 5

[params]
  # Subtitle of the website
  subtitle = "A collection of scores on myriad subjects."
  # Customize the indicator for margin notes
  marginNoteInd = "📎"
  # Your name or the name of you company
  copyright = "Copyright 2024"
  copyrightHolder = "Melody Henrich"
  # Show the "Powered by Hugo-Tufte and Hugo."
  showPoweredBy = false
  # Site wide kill switch for date in pages
  hidedate = false
  # Site wide kill switch for post summary on home page
  showSummary = true
  # ######## Common social website links, please comment the unused ones.
  # (if your favorite one is not in the list, please head to the footer menu below and add an entry)
  # Please note that some of the value below are only provided as an exemple, perhaps the computed isn't valid
  github = "mixolydianmel"
  # gitlab = slashformotion
  linkedin = "mixolydianmel"
  # twitter = slashformotion
  # patreon = ''
  # youtube = user/ChromeDevelopers # check the end of your youtube url https://www.youtube.com/<copy_this>
  # medium = slashformotion
  # reddit = Slashformotion
  # stackoverflow = 16609732/slashformotion
  instagram = "mixolydianmel"
  # mastodon = instance.url/@username
  # orcid = 0000-0003-0634-3275
  # google_scholar = jm5QaHkAAAAJ

[menu]
  [[menu.nav]]
    name = "Home"
    weight = -110
    identifier = "home"
    url = "/"

  [[menu.nav]]
    name = "Posts"
    weight = -110
    identifier = "posts"
    url = "/posts/"

  [[menu.nav]]
    name = "Source Code"
    weight = -70
    identifier = "github"
    url = "https://github.com/mixolydianmel/mixolydianmel.github.io"
